spring.datasource.url=jdbc:postgresql://localhost:5432/match_me
spring.datasource.username=match_me_user
spring.datasource.password=match_me_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tells Spring Boot to let Liquibase handle the schema
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=${JWT_SECRET:changethissecrettoalongrandombefore_production}
jwt.expiration=604800000

server.port=8080
